plugins {
    alias(libs.plugins.android.application)
}

def hasInjectedSigning = providers.gradleProperty('android.injected.signing.store.file').isPresent()

android {
    namespace 'me.bingyue.fuckbiliads'
    compileSdk 34

    defaultConfig {
        applicationId "me.bingyue.fuckbiliads"
        minSdk 27
        targetSdk 34
        versionCode 8
        versionName "4.2"

    }

    signingConfigs {
        release {
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
            enableV4Signing false
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            if (hasInjectedSigning) {
                signingConfig signingConfigs.release
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }



    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        resources {
            merges += 'META-INF/xposed/*'
        }
    }
}

androidComponents {
    onVariants(selector().withBuildType('release')) { variant ->
        if (variant.signingConfig != null) {
            variant.signingConfig.enableV1Signing.set(true)
            variant.signingConfig.enableV2Signing.set(true)
            variant.signingConfig.enableV3Signing.set(true)
            variant.signingConfig.enableV4Signing.set(false)
        }
    }
}

dependencies {
    compileOnly libs.libxposed.api
}
